### ISSUE TITLE
Extract iso-surface from a unsigned distance field? 

### ISSUE THREAD

**Issue by skanti** [mkazhdan/IsoSurfaceExtraction#2]
Hi,
I tried your code but it does not seem to work for unsigned distance fields? That means, a voxel grid with positive only voxel values e.g. [0, 100.0].

Can you confirm?

**Comment by mkazhdan** [comment]
It should work. You just need to provide the target iso-value using the "--iso" flag. (The default value of zero won't work in your case because, as the minimum of the implicit function, it is a critical point. Thus the the implicit function theorem does not hold and you do not get a surface. However, using an iso-value slightly bigger than zero should be ok.)

**Comment by skanti** [comment]
sweet thanks for the quick respond. It indeed works but the output is not the greatest, I think Marching Cubes really works the best if there is a zero-crossing.
